(planet

 (name "Planet Scheme")
 (link "https://planet.scheme.org/")
 (owner-name "The Scheme.org Community")
 (owner-email "schemeorg@srfi.schemers.org")
 (items-per-page 15)
 (days-per-page 100)
 (date-format "%A, %B %-d, %Y")

 (feeds
  ; missing (feed (url "http://my.opera.com/arcfide/xml/atom/blog/scheme/") (name "Aaron W. Hsu"))
  (feed (url "https://www.upyum.com/en/feed/scheme.atom")
        (name "Adrien Ramos"))
  (feed (url "https://www.snell-pym.org.uk/categories/sci-tech/computing/scheme/feed/atom/")
        (name "Alaric Snell-Pym"))
  ; 404 (feed (url "https://amirouche.dev/scheme.rss.xml") (name "Amirouche Amazigh BOUBEKKI"))
  (feed (url "https://andrewwhaley.blogspot.com/feeds/posts/default/-/scheme")
        (name "Andrew Whaley"))
  (feed (url "https://wingolog.org/feed/atom?with=guile&with=scheme")
        (name "Andy Wingo"))
  (feed (url "https://speechcode.com/blog/label/scheme/rss")
        (name "Arthur A. Gleckler"))
  (feed (url "http://feeds.feedburner.com/bendiken/lisp")
        (name "Arto Bendiken"))
  (feed (url "https://www.blogbyben.com/feeds/posts/default/-/scheme")
        (name "Ben Simon"))
  (feed (url "https://gazette.call-cc.org/feed.atom")
        (name "Chicken Gazette"))
  (feed (url "http://pestilenz.org/~ckeen/blog/scheme.atom")
        (name "Christian Kellermann"))
  (feed (url "https://crumbles.blog/atom.xml")
        (name "crumbles.blog"))
  (feed (url "https://hashcollision.blogspot.com/feeds/posts/default/-/scheme")
        (name "Danny Yoo"))
  ; 404 (feed (url "https://dpk.land/blog/tags/scheme.xml") (name "Daphne Preston-Kendal"))
  (feed (url "https://calculist.blogspot.com/atom.xml")
        (name "Dave Herman"))
  (feed (url "https://theschemeway.blogspot.com/atom.xml")
        (name "Dominique Boucher"))
  (feed (url "http://drschemer.blogspot.com/atom.xml")
        (name "Doug Williams"))
  (feed (url "https://blog.practical-scheme.net/gauche?c=rss")
        (name "Gauche Devlog"))
  ; no feed (feed (url "https://www.gnu.org/software/guix/news/feed.xml") (name "GNU Guix"))
  (feed (url "https://www.wisdomandwonder.com/tag/Scheme/feed")
        (name "Grant Rettke"))
  (feed (url "https://www.greghendershott.com/feeds/Racket.atom.xml")
        (name "Greg Hendershott"))
  (feed (url "http://savannah.gnu.org/news/atom.php?group=guile")
        (name "Guile News"))
  (feed (url "https://weinholt.se/feed-scheme.xml")
        (name "Gwen Weinholt"))
  (feed (url "https://curiousprogrammer.wordpress.com/tag/scheme/feed/")
        (name "Ian O"))
  (feed (url "https://idiomdrottning.org/blog/programs")
        (name "Idiomdrottning"))
  (feed (url "https://keepworkingworkerbee.blogspot.com/atom.xml")
        (name "Jacob Matthews"))
  ; 404 (feed (url "http://jlongster.com/feeds/blog_rss/") (name "James Long"))
  ; 404 (feed (url "https://jeapostrophe.github.io/atom.xml") (name "Jay McCarthy"))
  (feed (url "http://www.scheme.dk/blog/atom.xml")
        (name "Jens Axel Søgaard"))
  (feed (url "https://soegaard.github.io/feeds/all.atom.xml")
        (name "Jens Axel Søgaard"))
  ; 404 (feed (url "https://jeremykun.com/tag/racket/feed/") (name "Jeremy Kun"))
  (feed (url "https://funcall.blogspot.com/feeds/posts/default/-/scheme")
        (name "Joe Marshall"))
  (feed (url "https://jointhefreeworld.org/rss.xml")
        (name "jointhefreeworld"))
  (feed (url "http://salty-schemer.blogspot.com/atom.xml")
        (name "Joshua Herman"))
  (feed (url "https://rednosehacker.com/feed/")
        (name "Jérémy Korwin-Zmijowski"))
  (feed (url "https://lips.js.org/blog/rss.xml")
        (name "LIPS Scheme Blog"))
  (feed (url "https://xacc.wordpress.com/category/ironscheme/feed/")
        (name "Llewellyn Pritchard"))
  (feed (url "http://mjr.towers.org.uk/blog/scheme.rss")
        (name "M J Ray"))
  (feed (url "https://www.unsyntax.org/feed.xml")
        (name "Marc Nieper-Wikirchen"))
  (feed (url "https://mdhughes.tech/category/scheme/feed/")
        (name "Mark Damon Hughes"))
  ; format (feed (url "http://feeds2.feedburner.com/PmatosMinority-Scheme") (name "Paulo Jorge Matos"))
  (feed (url "http://per.bothner.com/blog/Scheme/index.atom")
        (name "Per Bothner"))
  (feed (url "https://www.more-magic.net/feed.atom")
        (name "Peter Bex"))
  (feed (url "https://pschombe.wordpress.com/feed/")
        (name "Peter Schombert"))
  ; format (feed (url "http://phildawes.net/blog/tag/scheme/atom.xml") (name "Phil Dawes"))
  (feed (url "https://programmingpraxis.com/feed/")
        (name "Programming Praxis"))
  (feed (url "https://retropikzel.neocities.org/feed.xml")
        (name "Retropikzel's blog"))
  (feed (url "https://macrologist.blogspot.com/atom.xml")
        (name "Ryan Culpepper"))
  (feed (url "https://scriptstoprograms.wordpress.com/feed/")
        (name "Sam Tobin-Hochstadt"))
  (feed (url "https://srfi.schemers.org/srfi.rss")
        (name "Scheme Requests for Implementation"))
  ; 404 (feed (url "http://racketista.com/atom.xml") (name "Sergi Mansilla"))
  (feed (url "https://spritely.institute/feed.xml")
        (name "spritely.institute"))
  (feed (url "https://blog.racket-lang.org/feeds/all.atom.xml")
        (name "The Racket Blog"))
  (feed (url "https://shisaa.be/categories/scheme.xml")
        (name "Tim van der Linden"))
  (feed (url "https://emacsninja.com/scheme.atom")
        (name "Vasilij Schneidermann"))
  (feed (url "https://lockywolf.wordpress.com/tag/scheme/feed/")
        (name "Vladimir Nikishkin"))
  (feed (url "https://wmfarr.blogspot.com/atom.xml")
        (name "Will Farr"))
  (feed (url "https://feeds.feedburner.com/WebDevelopmentFunctionalProgrammingAndScheme")
        (name "Yinso Chen"))
  (feed (url "https://littlewingpinball.wordpress.com/category/scheme/feed/")
        (name "Yoshikatsu Fujita"))))
